name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./doc/requirements.txt

      - run: |
          mkdocs build -f ./doc/mkdocs.yml -d ../site/Module10
          ls -lR ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: momosk-dt/Piper-for-Partner-2020
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site